name: Comment on PR with framework coverage changes

on:
  workflow_run:
    workflows: ["Check framework coverage changes"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Clone self (github/codeql) head
      uses: actions/checkout@v2
      with:
        path: head
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # download artifacts from the PR job:
    - name: Download artifact - HEAD
      uses: dawidd6/action-download-artifact@v2.14.0
      with:
        workflow: csv-coverage-pr-artifacts.yml
        run_id: ${{ github.event.workflow_run.id }}
        name: csv-framework-coverage-merge
        path: out_head

    - name: Download artifact - BASE
      uses: dawidd6/action-download-artifact@v2.14.0
      with:
        workflow: csv-coverage-pr-artifacts.yml
        run_id: ${{ github.event.workflow_run.id }}
        name: csv-framework-coverage-base
        path: out_base

    - name: Download artifact - PR
      uses: dawidd6/action-download-artifact@v2.14.0
      with:
        workflow: csv-coverage-pr-artifacts.yml
        run_id: ${{ github.event.workflow_run.id }}
        name: pr
        path: pr

    - name: Check coverage files
      run: |
        PR=$(cat "pr/NR")
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} python head/misc/scripts/library-coverage/compare-files-comment-pr.py \
          out_head out_base comparison.md ${{ github.repository }} $PR ${{ github.event.workflow_run.id }}
    - name: Upload comparison results
      uses: actions/upload-artifact@v2
      with:
        name: comparison
        path: |
          comparison.md
